baseURL = 'https://aaron-randreth.github.io/'
languageCode = 'fr'
title = 'Cours'
theme = 'lugo'
SectionPagesMenu = 'main'


[params]
    favicon = 'favicon.svg'
    css = ["style.css", "nav.css", "footer.css"]

